### ISSUE TITLE
change OpenRouteService to openroutservice

### ISSUE THREAD

**Issue by TheGreatRefrigerator** [Dhi13man/open_route_service#7] opened 2021-09-26 12:34 UTC
OpenRouteService is a deprecated notation.
Please use openrouteservice (Start of record: Openrouteservice; abbr: ORS) instead.

**Comment by Dhi13man** [comment] 2021-09-26 13:17
Is this about the Class name? The class name is following UpperCamelCase convention. Do let me know if the issue is regarding something else. Or better yet, fork the repo and make a PR with the change you have in mind. :)

**Comment by TheGreatRefrigerator** [comment] 2021-09-26 13:24
No, not about the class name, more like the general naming in readme and comments.
Regarding convention i would suggest class names such as `ORSDirections` instead to keep it short.

**Comment by TheGreatRefrigerator** [comment] 2021-09-26 13:26
Not too much time at my hand right now, but i will see what i can do.

**Comment by Dhi13man** [comment] 2021-09-26 13:51
Resolved in latest commits [bb1a7dda0114391bf5ed22bbb732465fd35ae834](https://github.com/Dhi13man/open_route_service/commit/bb1a7dda0114391bf5ed22bbb732465fd35ae834) and [6f9825fd228ba10594051accf3d7060e869ddb97](https://github.com/Dhi13man/open_route_service/commit/6f9825fd228ba10594051accf3d7060e869ddb97). 

Closing for now. Thank you for the information. I wasn't aware of the convention.

**Closed as completed by Dhi13man** 2021-09-26 13:51 UTC
